require: 
  - rubocop-rails
  - rubocop-rspec

# AllCops settings
AllCops:
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*
    - tmp/**/*

# Line length
Metrics/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Metrics/ParameterLists:
  CountKeywordArgs: false

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - unless
    - for

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 7

RSpec/ExampleLength:
  Enabled: false

Style/Documentation:
  Enabled: false
