version: "3.3"
services:
  app:
    build: .
    command: ["bundle", "exec", "./bin/rails", "server", "-p", "3000", "-b", "0.0.0.0"]
    container_name: app_container
    tty: true
    stdin_open: true
    volumes:
      - .:/rails
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      POSTGRES_HOST: db
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "3000:3000"
    entrypoint: bin/docker-entrypoint
    networks:
      - backend

  jobs:
    build: .
    command: ["bundle", "exec", "whenever", "--update-crontab", "&&", "cron", "-f"]
    container_name: jobs_container
    volumes:
      - .:/rails
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      POSTGRES_HOST: db
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    entrypoint: bin/docker-whenever-entrypoint
    networks:
      - backend

  db:
    image: postgres
    container_name: db_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres:
networks:
  backend:
    driver: "bridge"