default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["MYSQL_USERNAME"] || "root" %>
  password: <%= ENV["MYSQL_PASSWORD"] || "root" %>
  host: <%= ENV["MYSQL_HOST"] || "localhost" %>

development:
  <<: *default
  database: "payment_test_app_development"

test:
  <<: *default
  database: "payment_test_app_test"

production:
  <<: *default
  database: payment_test_app_production
  username: <%= ENV["MYSQL_USERNAME"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  host: <%= ENV["MYSQL_HOST"] %>
  port: <%= ENV["MYSQL_PORT"] %>