default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["POSTGRES_USERNAME"] || "postgres" %>
  password: <%= ENV["POSTGRES_PASSWORD"] || "postgres" %>
  host: <%= ENV["POSTGRES_HOST"] || "localhost" %>

development:
  <<: *default
  database: "payment_test_app_development"

test:
  <<: *default
  database: "payment_test_app_test"

production:
  <<: *default
  database: payment_test_app_production
  username: <%= ENV["MYSQL_USERNAME"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  host: <%= ENV["MYSQL_HOST"] %>
  port: <%= ENV["MYSQL_PORT"] %>